services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: dw
      POSTGRES_PASSWORD: dw
      POSTGRES_DB: ecommerce_dw
    ports:
      - "5433:5432"

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD:-Dev_Str0ng_Pass!}"
    ports:
      - "1433:1433"
